### ISSUE TITLE
Mistake in file: "run-pyscf.py" wrong bracket

### ISSUE THREAD

**Issue by RealUranar** [andreagrisafi/SALTED#18]
In the file "run-pyscf.py" on line 73

```np.save(os.path.join(inp.path2qm, "density_matrices", f"dm_conf{iconf+1}.npy", dm))```
should be:
```np.save(os.path.join(inp.path2qm, "density_matrices", f"dm_conf{iconf+1}.npy"), dm)```

**Comment by nqhq-lou** [comment]
Thank you very much! We started a pull request #19 to fix this.

**Comment by andreagrisafi** [comment]
that is fixed

**Comment by RealUranar** [comment]
Thank you!
