### ISSUE TITLE
Error when using the newest version of rascaline

### ISSUE THREAD

**Issue by RealUranar** [andreagrisafi/SALTED#20]
The developers of rascaline changed their naming scheme in their newest commit.

It changes (if i got this correctly):
species_center -> center_type
species_neighbor -> neighbor_type
spherical_harmonics_l -> o3_lambda and o3_sigma

This breaks ```equirepr.py```  around line 190 and line 239,
and ```equipred.py``` around line 222 and line 264.

**Comment by nqhq-lou** [comment]
Thanks for your feedback! Rascaline is under active development.
Please use a past version, like `python -m pip install --no-cache-dir git+https://github.com/Luthaf/rascaline.git@2851d47ab3471057f3794ac2b48b0417add2f748`, which is `rascaline==0.1.0.dev491`.
We will look into this later.

**Comment by RealUranar** [comment]
Ok i will do that, thank you.

**Comment by andreagrisafi** [comment]
this is now solved.
