### ISSUE TITLE
String size too short

### ISSUE THREAD

**Issue by mahrossi** [andreagrisafi/SALTED#5]
Hey @andreagrisafi and @alanmlewis - this is probably an issue that may not appear in the current version as I see you seem to have gotten rid of `matrices.f90`, but just in case, I write it here. In the current `legacy` branch, the sizes of the strings in line 7 of `matrices.f90` 

`CHARACTER*64:: dirker,dirover,dirprojs`

quickly become too short if a user has long paths to the directory where SALTED is. This breaks the code only with core dumps if things are too big. The fix is simple, just making the character length 1024 or so. But again, I guess you will not need this anymore?

**Comment by andreagrisafi** [comment]
Hi @mahrossi, thanks for spotting this issue. We indeed got rid entirely of `matrices.f90` in the current version of the code and we no longer read from fortran the path to the SALTED directory.
